[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Flask app build completed'"]

[start]
cmd = "python app.py"

[variables]
PYTHONPATH = "/app"
FLASK_ENV = "production"
PORT = "5000"
